# -*- coding: utf-8 -*-
"""cian_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nc_OaWDb3mDg71PbGmv5JrGHYezEI0qI

Анализ данных о недвижимости с CIAN
"""

# Этап 1. Сбор данных (Парсинг)

import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
import time
import random

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
]

def get_headers():
    return {
        "User-Agent": random.choice(USER_AGENTS),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
        "Accept-Language": "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3",
        "Accept-Encoding": "gzip, deflate, br",
        "Connection": "keep-alive",
        "Upgrade-Insecure-Requests": "1",
    }

# Функция для получения списка объявлений с поисковой выдачи
def get_offers_list(page=1):
    """Получает список объявлений с поисковой выдачи Циан"""
    url = f"https://www.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p={page}&region=1"

    try:
        response = requests.get(url, headers=get_headers(), timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')
        offers = []

        # Ищем карточки объявлений
        offer_cards = soup.find_all('article', {'data-name': 'CardComponent'})

        for card in offer_cards:
            try:
                # Извлекаем ID объявления
                link_elem = card.find('a', href=re.compile(r'/sale/flat/\d+/'))
                if not link_elem:
                    continue

                href = link_elem.get('href', '')
                offer_id = re.search(r'/sale/flat/(\d+)/', href)
                if offer_id:
                    offer_id = offer_id.group(1)

                    # Основная информация
                    title_elem = card.find('span', {'data-mark': 'OfferTitle'})
                    price_elem = card.find('span', {'data-mark': 'MainPrice'})

                    title = title_elem.text.strip() if title_elem else ''
                    price = price_elem.text.strip() if price_elem else ''

                    # Адрес
                    address_elem = card.find('a', {'data-name': 'AddressItem'})
                    address = address_elem.text.strip() if address_elem else ''

                    offers.append({
                        'id': offer_id,
                        'title': title,
                        'price': price,
                        'address': address,
                        'url': f"https://www.cian.ru/sale/flat/{offer_id}/"
                    })

            except Exception as e:
                print(f"Ошибка парсинга карточки: {e}")
                continue

        return offers

    except Exception as e:
        print(f"Ошибка получения страницы {page}: {e}")
        return []

# Функция для парсинга детальной информации
def parse_property_info(text):
    result = {}

    # Общая площадь
    total_match = re.search(r'Общая\s+площадь\s*([\d,]+)\s*м²', text)
    if total_match:
        result['total_area'] = total_match.group(1).replace(',', '.')

    # Площадь кухни
    kitchen_match = re.search(r'Площадь\s+кухни\s*([\d,]+)\s*м²', text)
    if kitchen_match:
        result['kitchen_area'] = kitchen_match.group(1).replace(',', '.')

    # Жилая площадь
    living_match = re.search(r'Жилая\s+площадь\s*([\d,]+)\s*м²', text)
    if living_match:
        result['living_area'] = living_match.group(1).replace(',', '.')

    # Этаж
    floor_match = re.search(r'Этаж\s*(\d+)\s*из\s*(\d+)', text)
    if floor_match:
        result['floor'] = floor_match.group(1)
        result['total_floors'] = floor_match.group(2)

    # Год постройки
    year_match = re.search(r'Год\s+постройки\s*(\d+)', text)
    if year_match:
        result['build_year'] = year_match.group(1)

    # Количество комнат
    rooms_match = re.search(r'(\d+)-?комнат', text.lower())
    if rooms_match:
        result['rooms'] = rooms_match.group(1)
    elif 'студия' in text.lower():
        result['rooms'] = '0'

    # Тип дома
    if 'панел' in text.lower():
        result['house_type'] = 'панельный'
    elif 'монолит' in text.lower():
        result['house_type'] = 'монолитный'
    elif 'кирпич' in text.lower():
        result['house_type'] = 'кирпичный'
    elif 'блоч' in text.lower():
        result['house_type'] = 'блочный'
    elif 'дерев' in text.lower():
        result['house_type'] = 'деревянный'

    return result

# Функция для парсинга детальной страницы объявления
def parse_offer_detail(offer_id):
    """Парсит детальную информацию об объявлении"""
    url = f'https://www.cian.ru/sale/flat/{offer_id}/'

    try:
        response = requests.get(url, headers=get_headers(), timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, 'html.parser')

        # Адрес
        address_elem = soup.find('div', {'data-testid': 'object-address'})
        address = address_elem.text.strip() if address_elem else ''

        # Метро
        metro_items = soup.find_all('a', href=re.compile(r'/metro/'))
        stations = []
        for metro in metro_items:
            station_text = metro.text.strip()
            if station_text and 'метро' in station_text.lower():
                stations.append(station_text)

        # Цена
        price_elem = soup.find('div', {'data-testid': 'price-amount'})
        price = price_elem.text.strip() if price_elem else ''

        # Характеристики
        features = {}
        feature_elems = soup.find_all('div', class_=re.compile(r'feature'))

        for elem in feature_elems:
            text = elem.text.strip().lower()
            if 'общая' in text and 'м²' in text:
                area_match = re.search(r'(\d+[,.]?\d*)\s*м²', text)
                if area_match:
                    features['total_area'] = area_match.group(1).replace(',', '.')
            elif 'кухня' in text and 'м²' in text:
                area_match = re.search(r'(\d+[,.]?\d*)\s*м²', text)
                if area_match:
                    features['kitchen_area'] = area_match.group(1).replace(',', '.')
            elif 'этаж' in text:
                floor_match = re.search(r'(\d+)\s*из\s*(\d+)', text)
                if floor_match:
                    features['floor'] = floor_match.group(1)
                    features['total_floors'] = floor_match.group(2)
            elif 'комнат' in text:
                rooms_match = re.search(r'(\d+)\s*комнат', text)
                if rooms_match:
                    features['rooms'] = rooms_match.group(1)
                elif 'студия' in text:
                    features['rooms'] = '0'

        # Если не нашли через features, пробуем альтернативный способ
        if not features:
            factoid_text = soup.get_text()
            features = parse_property_info(factoid_text)

        # Описание
        desc_elem = soup.find('div', {'data-testid': 'object-description'})
        description = desc_elem.text.strip() if desc_elem else ''

        return {
            'id': offer_id,
            'address': address,
            'stations': stations,
            'price': price,
            'features': features,
            'description': description
        }

    except Exception as e:
        print(f"Ошибка парсинга объявления {offer_id}: {e}")
        return None

def main():
    all_offers = []

    # Собираем список объявлений с первых 3 страниц
    print("Собираем список объявлений...")
    for page in range(1, 4):
        print(f"Страница {page}...")
        offers = get_offers_list(page)
        all_offers.extend(offers)
        print(f"Найдено {len(offers)} объявлений")
        time.sleep(random.uniform(1, 2))

    print(f"Всего собрано {len(all_offers)} объявлений")

    # Парсим детальную информацию
    detailed_data = []
    for i, offer in enumerate(all_offers):
        print(f"Парсим объявление {i+1}/{len(all_offers)} (ID: {offer['id']})")

        detail = parse_offer_detail(offer['id'])
        if detail:
            # Объединяем базовую и детальную информацию
            merged_offer = {**offer, **detail}
            detailed_data.append(merged_offer)

        time.sleep(random.uniform(0.5, 1))

    if detailed_data:
        df = pd.DataFrame(detailed_data)

        features_df = pd.json_normalize(df['features'])
        df = pd.concat([df.drop('features', axis=1), features_df], axis=1)

        # Сохраняем результат
        df.to_csv('cian_parsed.csv', index=False, encoding='utf-8')
        print(f"Файл сохранен! Всего объявлений: {len(df)}")

        # Статистика
        print("\nСобраны данные:")
        print(f"- Всего объявлений: {len(df)}")
        print("\nДоступные поля:")
        for col in df.columns:
            non_empty = df[col].notna().sum()
            print(f"  - {col}: {non_empty} заполненных значений")
    else:
        print("Не удалось собрать данные")

if __name__ == "__main__":
    main()

import requests
from bs4 import BeautifulSoup
import collections
import csv
import re
import time

ParseResults = collections.namedtuple(
    'ParseResults',
    {
        'offer_id',
        'title',
        'address',
        'district',
        'price',
        'total_area',
        'rooms',
        'floor',
        'floors_total',
        'house_type',
        'year_built',
        'description'
    }
)

class CianParser:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept-Language': 'ru'
        }
        self.result = []
        # Добавляем заголовки
        self.result.append(ParseResults(
            offer_id='offer_id',
            title='title',
            address='address',
            district='district',
            price='price',
            total_area='total_area',
            rooms='rooms',
            floor='floor',
            floors_total='floors_total',
            house_type='house_type',
            year_built='year_built',
            description='description'
        ))

    def load_page(self, page=1):
        """Загрузка страницы с объявлениями"""
        url = f"https://www.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p={page}&region=1"
        try:
            res = self.session.get(url=url, timeout=10)
            res.raise_for_status()
            return res.text
        except Exception as e:
            print(f"Ошибка загрузки страницы {page}: {e}")
            return None

    def parse_page(self, html: str):
        """Парсинг списка объявлений на странице"""
        if not html:
            return

        soup = BeautifulSoup(html, 'lxml')
        offers = soup.select("article[data-name='CardComponent']")

        print(f"Найдено объявлений на странице: {len(offers)}")

        for block in offers:
            try:
                self.parse_block(block=block)
                time.sleep(0.5)  # Задержка между запросами
            except Exception as e:
                print(f"Ошибка парсинга блока: {e}")
                continue

    def parse_block(self, block):
        """Парсинг отдельного объявления из списка"""
        # ID объявления
        link_elem = block.select("a[data-name='Link']")[0]
        link = link_elem.get('href', '')
        offer_id = re.search(r'/(\d+)/', link)
        offer_id = offer_id.group(1) if offer_id else ''

        # Заголовок
        title_elem = block.select("span[data-mark='OfferTitle']")
        title = title_elem[0].text.strip() if title_elem else ''

        # Адрес и район
        address_elem = block.select("a[data-name='AddressItem']")
        address_full = address_elem[0].text.strip() if address_elem else ''

        # Разделяем адрес и район
        address_parts = [part.strip() for part in address_full.split(',')]
        address = address_parts[-1] if address_parts else ''
        district = address_parts[-2] if len(address_parts) > 1 else ''

        # Цена
        price_elem = block.select("span[data-mark='MainPrice']")
        price_text = price_elem[0].text.strip() if price_elem else ''
        price = re.sub(r'[^\d]', '', price_text) if price_text else '0'

        # Основные характеристики из заголовка
        rooms, total_area, floor_info = self.parse_title_info(title)

        # Этажи
        floor, floors_total = self.parse_floor_info(floor_info)

        # Загружаем детальную страницу для дополнительной информации
        house_type, year_built, description = self.parse_detail_page(offer_id)

        # Добавляем результат
        self.result.append(ParseResults(
            offer_id=offer_id,
            title=title,
            address=address,
            district=district,
            price=price,
            total_area=total_area,
            rooms=rooms,
            floor=floor,
            floors_total=floors_total,
            house_type=house_type,
            year_built=year_built,
            description=description
        ))

        print(f"Обработано объявление {offer_id}: {title}")

    def parse_title_info(self, title):
        """Парсинг информации из заголовка"""
        rooms = 0
        total_area = 0
        floor_info = ""

        # Количество комнат
        if 'студия' in title.lower():
            rooms = 0
        else:
            rooms_match = re.search(r'(\d+)-комн', title.lower())
            rooms = rooms_match.group(1) if rooms_match else ''

        # Площадь
        area_match = re.search(r'(\d+[,.]?\d*)\s*м²', title.lower())
        total_area = area_match.group(1).replace(',', '.') if area_match else ''

        # Этажи
        floor_match = re.search(r'(\d+)\s*/\s*(\d+)\s*эт', title.lower())
        if floor_match:
            floor_info = f"{floor_match.group(1)}/{floor_match.group(2)}"

        return rooms, total_area, floor_info

    def parse_floor_info(self, floor_info):
        """Парсинг информации о этажах"""
        if floor_info and '/' in floor_info:
            parts = floor_info.split('/')
            return parts[0], parts[1]
        return '', ''

    def parse_detail_page(self, offer_id):
        """Парсинг детальной страницы объявления"""
        house_type = ''
        year_built = ''
        description = ''

        try:
            url = f"https://www.cian.ru/sale/flat/{offer_id}/"
            res = self.session.get(url=url, timeout=10)
            res.raise_for_status()

            soup = BeautifulSoup(res.text, 'lxml')

            # Тип дома
            house_elems = soup.find_all('div', string=re.compile(r'Тип дома', re.IGNORECASE))
            for elem in house_elems:
                next_elem = elem.find_next_sibling('div')
                if next_elem:
                    house_type = next_elem.text.strip()
                    break

            # Год постройки
            year_elems = soup.find_all('div', string=re.compile(r'Год постройки', re.IGNORECASE))
            for elem in year_elems:
                next_elem = elem.find_next_sibling('div')
                if next_elem:
                    year_text = next_elem.text.strip()
                    year_match = re.search(r'\d{4}', year_text)
                    year_built = year_match.group() if year_match else ''
                    break

            # Описание
            desc_elem = soup.find('div', {'data-name': 'Description'})
            if desc_elem:
                description = desc_elem.text.strip()[:200]  # Ограничиваем длину

        except Exception as e:
            print(f"Ошибка парсинга детальной страницы {offer_id}: {e}")

        return house_type, year_built, description

    def save_results(self):
        """Сохранение результатов в CSV"""
        filename = "cian_raw.csv"
        with open(filename, "w", newline='', encoding='utf-8') as f:
            writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
            for item in self.result:
                writer.writerow(item)
        print(f"Результаты сохранены в {filename}")

    def run(self):
        """Основной метод запуска парсера"""
        print("Начинаем парсинг Циан...")

        for page in range(1, 4):  # Первые 3 страницы
            print(f"Парсинг страницы {page}...")
            html = self.load_page(page=page)
            if html:
                self.parse_page(html=html)
            time.sleep(1)  # Задержка между страницами

        print(f"Парсинг завершен. Собрано {len(self.result) - 1} объявлений")

if __name__ == '__main__':
    parser = CianParser()
    parser.run()
    parser.save_results()

# Этап 2. Очистка и нормализация данных

import pandas as pd
import numpy as np
import ast
import re

# Чтение данных
df = pd.read_csv('cian_raw.csv')

# Просмотр структуры данных
print("Исходные колонки:")
print(df.columns.tolist())
print(f"\nРазмер данных: {df.shape}")
print("\nПервые 2 строки:")
print(df.head(2))

# Функция для извлечения количества комнат
def extract_rooms(title, address):
    """Извлекает количество комнат из заголовка или адреса"""
    if pd.isna(title):
        title = ""
    if pd.isna(address):
        address = ""

    text = f"{title} {address}".lower()

    # Поиск паттернов комнат
    patterns = [
        r'(\d+)-комн',
        r'(\d+)комн',
        r'(\d+)-к',
        r'(\d+)к',
        r'студи'
    ]

    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            if 'студи' in pattern:
                return 0
            return int(match.group(1))

    return None

# Функция для определения типа дома
def get_house_type(parsed_info, address):
    """Определяет тип дома на основе данных"""
    if pd.isna(address):
        address = ""

    address_lower = address.lower()

    # Проверяем по ключевым словам в адресе
    if any(word in address_lower for word in ['панел', 'панельный']):
        return 'панельный'
    elif any(word in address_lower for word in ['монолит', 'монолитный']):
        return 'монолитный'
    elif any(word in address_lower for word in ['кирпич', 'кирпичный']):
        return 'кирпичный'
    elif any(word in address_lower for word in ['блоч', 'блочный']):
        return 'блочный'
    else:
        return 'не указан'

# Функция для очистки числовых значений
def clean_numeric(value, default=0):
    """Очищает числовые значения от лишних символов"""
    if pd.isna(value):
        return default

    try:
        # Удаляем все нечисловые символы, кроме точки и запятой
        cleaned = re.sub(r'[^\d,.]', '', str(value))
        # Заменяем запятую на точку
        cleaned = cleaned.replace(',', '.')
        return float(cleaned) if cleaned else default
    except:
        return default

# Создаем новый DataFrame с нужной структурой
cleaned_data = []

for idx, row in df.iterrows():
    try:
        # Парсинг parsed_data
        parsed_info = ast.literal_eval(row['parsed_data']) if pd.notna(row['parsed_data']) else {}

        # Основные данные
        offer_id = row['id']
        address = row['adress'] if pd.notna(row['adress']) else "Адрес не указан"

        # Извлечение района из адреса
        district_match = re.search(r'р-н\s+([^,]+)', address)
        district = district_match.group(1) if district_match else "Не указан"

        # Очистка цены
        price = clean_numeric(row['price'])

        # Очистка площади
        total_area = clean_numeric(parsed_info.get('total_area'))

        # Извлекаем количество комнат (ищем в других колонках)
        rooms = extract_rooms(
            row.get('title', ''),
            row.get('adress', '')
        )

        # Если не нашли комнаты, ставим None
        if rooms is None:
            rooms = None

        # Этаж и всего этажей
        floor = int(clean_numeric(parsed_info.get('floor')))
        floors_total = int(clean_numeric(parsed_info.get('total_floors')))

        # Создаем заголовок
        title_parts = []
        if rooms is not None:
            if rooms == 0:
                title_parts.append("Студия")
            else:
                title_parts.append(f"{rooms}-комн. квартира")
        if total_area > 0:
            title_parts.append(f"{total_area} м²")
        if floor > 0 and floors_total > 0:
            title_parts.append(f"{floor}/{floors_total} этаж")

        title = ", ".join(title_parts) if title_parts else "Квартира"

        # Тип дома
        house_type = get_house_type(parsed_info, address)

        # Год постройки
        year_built = int(clean_numeric(parsed_info.get('build_year'))) if parsed_info.get('build_year') else None

        # Описание (можно добавить больше информации)
        description = f"Квартира {total_area} м²" if total_area > 0 else "Квартира"

        cleaned_data.append({
            'offer_id': offer_id,
            'title': title,
            'address': address,
            'district': district,
            'price': price,
            'total_area': total_area,
            'rooms': rooms,
            'floor': floor,
            'floors_total': floors_total,
            'house_type': house_type,
            'year_built': year_built,
            'description': description
        })

    except Exception as e:
        print(f"Ошибка обработки строки {idx}: {e}")
        continue

# Создаем очищенный DataFrame
df_clean = pd.DataFrame(cleaned_data)

# Удаляем дубликаты по offer_id
initial_count = len(df_clean)
df_clean = df_clean.drop_duplicates(subset=['offer_id'])
final_count = len(df_clean)

print(f"\nУдалено дубликатов: {initial_count - final_count}")

# Заменяем 0 на None в числовых полях где это уместно
numeric_columns = ['rooms', 'floor', 'floors_total', 'year_built']
for col in numeric_columns:
    df_clean[col] = df_clean[col].replace(0, None)

# Сохраняем очищенные данные
df_clean.to_csv('cian_clean.csv', index=False, encoding='utf-8')

print(f"\nОчищенные данные сохранены. Размер: {df_clean.shape}")
print("\nСтатистика данных:")
print(f"Всего объявлений: {len(df_clean)}")
print(f"Заполнено цен: {df_clean['price'].notna().sum()}")
print(f"Заполнено площадей: {df_clean['total_area'].notna().sum()}")
print(f"Заполнено комнат: {df_clean['rooms'].notna().sum()}")
print(f"Заполнено этажей: {df_clean['floor'].notna().sum()}")

print("\nПервые 3 строки очищенных данных:")
print(df_clean.head(3))

print("\nИнформация о типах данных:")
print(df_clean.dtypes)

# Этап 3. Анализ данных

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Настройка визуализации
plt.style.use('default')
sns.set_palette("husl")

# Загрузка очищенных данных
df = pd.read_csv('cian_clean.csv')

print("=" * 60)
print("ЭТАП 3: АНАЛИЗ ДАННЫХ")
print("=" * 60)

# 1. ОПИСАНИЕ НАБОРА ДАННЫХ
print("\n1. ОПИСАНИЕ НАБОРА ДАННЫХ")
print("-" * 40)

print(f"Количество строк: {df.shape[0]}")
print(f"Количество столбцов: {df.shape[1]}")
print(f"\nТипы данных:")
print(df.dtypes)

print(f"\nПропуски в данных:")
missing_data = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100
missing_info = pd.DataFrame({
    'Кол-во пропусков': missing_data,
    'Процент пропусков': missing_percent.round(2)
})
print(missing_info)

print(f"\nДубликаты: {df.duplicated().sum()}")

# Основная статистика по числовым полям
print(f"\nОсновная статистика по числовым полям:")
print(df[['price', 'total_area', 'floor', 'floors_total', 'year_built']].describe().round(2))

# 2. ИССЛЕДОВАТЕЛЬСКИЙ АНАЛИЗ (EDA)
print("\n\n2. ИССЛЕДОВАТЕЛЬСКИЙ АНАЛИЗ (EDA)")
print("-" * 40)

# Добавляем расчет цены за кв. метр
df['price_per_sqm'] = df['price'] / df['total_area']

# Анализ по районам
print("\nАнализ по районам:")
district_stats = df.groupby('district').agg({
    'price': ['count', 'mean', 'median'],
    'total_area': 'mean',
    'price_per_sqm': 'mean',
    'floors_total': 'mean',
    'year_built': 'mean'
}).round(2)

district_stats.columns = ['Кол-во', 'Ср_цена', 'Мед_цена', 'Ср_площадь', 'Ср_цена_м2', 'Ср_этажность', 'Ср_год_постройки']
print(district_stats)

# Зависимость цены от площади
print(f"\nКорреляция цена-площадь: {df['price'].corr(df['total_area']):.3f}")

# Анализ этажности
print(f"\nСредняя этажность по районам:")
avg_floors_by_district = df.groupby('district')['floors_total'].mean().sort_values(ascending=False)
print(avg_floors_by_district.round(1))

# Анализ года постройки
print(f"\nРаспределение по годам постройки:")
year_stats = df['year_built'].describe()
print(year_stats)

# 3. ВИЗУАЛИЗАЦИИ
print("\n\n3. ВИЗУАЛИЗАЦИИ")
print("-" * 40)

# Создаем фигуру с subplots
fig, axes = plt.subplots(2, 2, figsize=(15, 12))
fig.suptitle('Анализ рынка недвижимости Москвы', fontsize=16, fontweight='bold')

# 3.1 Гистограмма распределения цен
axes[0, 0].hist(df['price'] / 1e6, bins=30, alpha=0.7, edgecolor='black')
axes[0, 0].set_xlabel('Цена (млн руб)')
axes[0, 0].set_ylabel('Количество')
axes[0, 0].set_title('Распределение цен на квартиры')
axes[0, 0].grid(True, alpha=0.3)

# Добавляем вертикальную линию для медианы
median_price = df['price'].median() / 1e6
axes[0, 0].axvline(median_price, color='red', linestyle='--',
                   label=f'Медиана: {median_price:.1f} млн')
axes[0, 0].legend()

# 3.2 Scatter-график «цена — площадь»
scatter = axes[0, 1].scatter(df['total_area'], df['price'] / 1e6,
                            alpha=0.6, c=df['floors_total'], cmap='viridis')
axes[0, 1].set_xlabel('Площадь (м²)')
axes[0, 1].set_ylabel('Цена (млн руб)')
axes[0, 1].set_title('Зависимость цены от площади')
axes[0, 1].grid(True, alpha=0.3)

# Добавляем colorbar для этажности
cbar = plt.colorbar(scatter, ax=axes[0, 1])
cbar.set_label('Этажность дома')

# 3.3 Столбчатая диаграмма средней цены по районам
price_by_district = df.groupby('district')['price'].mean() / 1e6
price_by_district_sorted = price_by_district.sort_values(ascending=False)

bars = axes[1, 0].bar(price_by_district_sorted.index, price_by_district_sorted.values,
                     color=sns.color_palette("husl", len(price_by_district_sorted)))
axes[1, 0].set_xlabel('Район')
axes[1, 0].set_ylabel('Средняя цена (млн руб)')
axes[1, 0].set_title('Средняя цена квартир по районам')
axes[1, 0].tick_params(axis='x', rotation=45)

# Добавляем значения на столбцы
for bar in bars:
    height = bar.get_height()
    axes[1, 0].text(bar.get_x() + bar.get_width()/2., height,
                   f'{height:.1f}', ha='center', va='bottom')

# 3.4 Цена за кв. метр по районам
price_sqm_by_district = df.groupby('district')['price_per_sqm'].mean()
price_sqm_by_district_sorted = price_sqm_by_district.sort_values(ascending=False)

bars2 = axes[1, 1].bar(price_sqm_by_district_sorted.index, price_sqm_by_district_sorted.values / 1000,
                      color=sns.color_palette("Set2", len(price_sqm_by_district_sorted)))
axes[1, 1].set_xlabel('Район')
axes[1, 1].set_ylabel('Цена за м² (тыс. руб)')
axes[1, 1].set_title('Средняя цена за м² по районам')
axes[1, 1].tick_params(axis='x', rotation=45)

# Добавляем значения на столбцы
for bar in bars2:
    height = bar.get_height()
    axes[1, 1].text(bar.get_x() + bar.get_width()/2., height,
                   f'{height:.0f}', ha='center', va='bottom')

plt.tight_layout()
plt.show()

# ДОПОЛНИТЕЛЬНЫЕ ВИЗУАЛИЗАЦИИ
print("\nДОПОЛНИТЕЛЬНЫЕ ВИЗУАЛИЗАЦИИ")

# Боксплот цен по районам
plt.figure(figsize=(12, 6))
df_boxplot = df.copy()
df_boxplot['price_millions'] = df_boxplot['price'] / 1e6

sns.boxplot(data=df_boxplot, x='district', y='price_millions')
plt.title('Распределение цен по районам (боксплот)')
plt.xlabel('Район')
plt.ylabel('Цена (млн руб)')
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Распределение площади
plt.figure(figsize=(10, 6))
plt.hist(df['total_area'], bins=20, alpha=0.7, edgecolor='black')
plt.xlabel('Площадь (м²)')
plt.ylabel('Количество')
plt.title('Распределение площади квартир')
plt.grid(True, alpha=0.3)
plt.show()

# Сводные результаты анализа
print("\n" + "=" * 60)
print("СВОДНЫЕ РЕЗУЛЬТАТЫ АНАЛИЗА")
print("=" * 60)

print(f"\n📊 ОСНОВНЫЕ МЕТРИКИ:")
print(f"• Средняя цена квартиры: {df['price'].mean() / 1e6:.1f} млн руб")
print(f"• Медианная цена: {df['price'].median() / 1e6:.1f} млн руб")
print(f"• Средняя площадь: {df['total_area'].mean():.1f} м²")
print(f"• Средняя цена за м²: {df['price_per_sqm'].mean() / 1000:.0f} тыс. руб")

print(f"\n🏙️ АНАЛИЗ ПО РАЙОНАМ:")
most_expensive = price_by_district_sorted.index[0]
cheapest = price_by_district_sorted.index[-1]
print(f"• Самый дорогой район: {most_expensive} ({price_by_district_sorted.iloc[0]:.1f} млн руб)")
print(f"• Самый бюджетный район: {cheapest} ({price_by_district_sorted.iloc[-1]:.1f} млн руб)")

print(f"\n📈 КОРРЕЛЯЦИИ:")
print(f"• Цена vs Площадь: {df['price'].corr(df['total_area']):.3f}")
print(f"• Цена vs Этаж: {df['price'].corr(df['floor']):.3f}")
print(f"• Площадь vs Год постройки: {df['total_area'].corr(df['year_built']):.3f}")

print(f"\n🏢 ЭТАЖНОСТЬ:")
print(f"• Средняя этажность домов: {df['floors_total'].mean():.1f} этажей")
print(f"• Самый высокий дом: {df['floors_total'].max()} этажей")

print(f"\n🏗️ ГОДЫ ПОСТРОЙКИ:")
print(f"• Средний год постройки: {df['year_built'].mean():.0f}")
print(f"• Самый старый дом: {df['year_built'].min():.0f}")
print(f"• Самый новый дом: {df['year_built'].max():.0f}")

# Этап 4. Генерация признаков (Feature Engineering)

import pandas as pd
import numpy as np

# Загрузка данных
df = pd.read_csv('cian_clean.csv')

print("ЭТАП 4: ГЕНЕРАЦИЯ ПРИЗНАКОВ")
print("=" * 40)

# Создаем копию
df_simple = df.copy()

print(f"Исходные колонки: {list(df_simple.columns)}")

# 1. ЦЕНА ЗА КВАДРАТНЫЙ МЕТР
df_simple['price_per_m2'] = df_simple['price'] / df_simple['total_area']

# 2. ПРИЗНАК НОВОСТРОЙКИ
df_simple['is_new_building'] = (df_simple['year_built'] >= 2010).astype(int)

# 3. ВОЗРАСТ ЗДАНИЯ
df_simple['building_age'] = 2025 - df_simple['year_built']

# 4. КОЭФФИЦИЕНТ ЭТАЖА
df_simple['floor_ratio'] = df_simple['floor'] / df_simple['floors_total']

# 5. РАССТОЯНИЕ ДО ЦЕНТРА (простая версия)
def simple_center_distance(district):
    if district in ['Тверской', 'Мещанский']:
        return 'center'
    else:
        return 'not_center'

df_simple['center_distance'] = df_simple['district'].apply(simple_center_distance)

print(f"\nСгенерировано 5 новых признаков:")
print("1. price_per_m2 - цена за м²")
print("2. is_new_building - новостройка (0/1)")
print("3. building_age - возраст здания")
print("4. floor_ratio - коэффициент этажа")
print("5. center_distance - расстояние до центра")

# Проверка новых признаков
print(f"\nПроверка новых признаков:")
print(df_simple[['price_per_m2', 'is_new_building', 'building_age', 'floor_ratio', 'center_distance']].head())

# Сохраняем результат
df_simple.to_csv('cian_simple_features.csv', index=False, encoding='utf-8')
print(f"\n✅ Данные сохранены в 'cian_simple_features.csv'")
print(f"✅ Итоговое количество колонок: {len(df_simple.columns)}")